          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 18
            pre_build:
              commands:
                - echo Retrieving information from artifacts...
            build:
              commands:
                - echo Building the parameters file..........
            post_build:
              commands:
                - echo source code to s3
                - zip folder1.zip folder1
                - aws s3 cp --recursive folder1 s3://ranibucket2/folder1.zip
       
